name: Tangle

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  tangle:
    runs-on: ubuntu-latest

    steps:
      - uses: gwennlbh/to-tangled@v0.3
        with:
          repo: tgirl.cloud/nix-templates
          ssh-key: ${{ secrets.TANGLED_KEY }}
